#32564 Contactgegevens inzien
valtimo-platform/valtimo-portal-engine pull request #101
Opened 2021-12-07 09:56 UTC by Klaas-Ritense

New module: 'klant'. The implementation was mostly copied from module 'zaak'

2021-12-07 10:04 UTC, mritense approved these changes

2021-12-08 12:06 UTC, ivo-ritense requested changes

2021-12-08 12:06 UTC, ivo-ritense commented on klant/src/main/kotlin/com/ritense/valtimo/portal/klant/domain/klanten/Klant.kt
> +    val url: String?,
Ik zou sowieso de data limiteren tot de properties die we nodig hebben.

2021-12-08 12:06 UTC, ivo-ritense commented on klant/src/main/kotlin/com/ritense/valtimo/portal/klant/graphql/KlantQuery.kt
> +    suspend fun getKlant(dfe: DataFetchingEnvironment): Klant? {
Willen we hier spreken over de Klant? Of gaat het om het ophalen van een Profiel? Als we straks Haal Centraal toevoegen, wordt dat dan deel van deze call of van een nieuwe?

2021-12-08 15:04 UTC, Klaas-Ritense commented on klant/src/main/kotlin/com/ritense/valtimo/portal/klant/client/OpenKlantTokenGenerator.kt
> +        if (secretKey.length < 32) {
Een secretKey van lengte 32 is best wel klein. Dit mogen we wmb best afdwingen zonder het te documenteren.

Maar in de toekomst willen we denk ik wel vastzetten aan welke eisen een secretKey moet voldoen.

2021-12-08 15:52 UTC, Klaas-Ritense commented on app/gzac/src/main/resources/config/application.yml
> +        rsin: 051845623
weggehaald

2021-12-08 15:53 UTC, Klaas-Ritense commented on klant/src/main/kotlin/com/ritense/valtimo/portal/klant/client/OpenKlantTokenGenerator.kt
> +            .claim("user_id", userId)
Denk ik ook. Dus heb ze gevuld.

"""User ID to use for the audit trail. Although these external API credentials are typically used by this API itself instead of a user, the user ID is required."""

2021-12-08 15:53 UTC, Klaas-Ritense commented on klant/src/main/kotlin/com/ritense/valtimo/portal/klant/domain/klanten/Klant.kt
> +    val url: String?,
Gelimiteerd

2021-12-08 16:47 UTC, ivo-ritense commented on klant/src/main/kotlin/com/ritense/valtimo/portal/klant/autoconfiguration/KlantAutoConfiguration.kt
> +    fun klantListQuery(burgerService: BurgerService): BurgerQuery {
Is het een list die hij terug geeft?

2021-12-08 16:47 UTC, ivo-ritense commented on klant/src/main/kotlin/com/ritense/valtimo/portal/klant/client/OpenKlantClient.kt
> +                    HttpClient.create().wiretap(true)
Ik denk dat we wiretap niet altijd willen doen. Misschien op basis van spring profile? Log level? Misschien helemaal niet?

2021-12-08 16:47 UTC, ivo-ritense commented on klant/src/main/kotlin/com/ritense/valtimo/portal/klant/client/OpenKlantTokenGenerator.kt
> +        if (secretKey.length < 32) {
Documenteren lijkt me sowieso wel handig. We moeten alleen bedenken in welke vorm we dat willen doen.

2021-12-09 08:17 UTC, Klaas-Ritense commented on klant/src/main/kotlin/com/ritense/valtimo/portal/klant/autoconfiguration/KlantAutoConfiguration.kt
> +    fun klantListQuery(burgerService: BurgerService): BurgerQuery {
aangepast

2021-12-13 15:45 UTC, ivo-ritense approved these changes

2021-12-13 15:58 UTC, merged