feature 32960 - Enabled document downloads using streams
valtimo-platform/valtimo-portal-engine pull request #109
Opened 2022-01-11 09:27 UTC by Rick-Ritense

Enabled rest methods for this application

Created a rest endpoint to download documents via streams

2022-01-11 09:50 UTC, Klaas-Ritense commented on zaak/src/main/kotlin/com/ritense/valtimo/portal/zaak/service/DownloadService.kt
> +interface DownloadService {
imo this should be named `DownloadResource` and should be in the `.web.rest` package

The other DownloadResource should then be in the `.web.rest.impl` package

2022-01-11 09:50 UTC, Klaas-Ritense commented on zaak/src/main/kotlin/com/ritense/valtimo/portal/zaak/web/rest/DownloadResource.kt
> + * Copyright 2015-2021 Ritense BV, the Netherlands.
2022 :p

2022-01-11 09:50 UTC, Klaas-Ritense commented on zaak/src/main/kotlin/com/ritense/valtimo/portal/zaak/web/rest/DownloadResource.kt
> +            .blockLast()
Maybe its needed to set the `Content-Type` also. But Im not sure

2022-01-11 09:50 UTC, Klaas-Ritense commented on zaak/src/main/kotlin/com/ritense/valtimo/portal/zaak/autoconfiguration/DocumentAutoConfiguration.kt
> +    fun documentResource(openZaakClient: OpenZaakClient): DownloadResource {
Typo. Should be `downloadResource`

2022-01-11 10:02 UTC, Rick-Ritense commented on zaak/src/main/kotlin/com/ritense/valtimo/portal/zaak/web/rest/DownloadResource.kt
> + * Copyright 2015-2021 Ritense BV, the Netherlands.
De licenseHeaderFile.template die in die package staat toont nog het jaartal 2021. Die file wordt gebruikt voor de controle dat de license tekst klopt. 

Daarnaast is het t/m jaartal niet belangrijk voor open source licenties

2022-01-11 10:02 UTC, ivo-ritense commented on zaak/src/main/kotlin/com/ritense/valtimo/portal/zaak/web/rest/DownloadResource.kt
> +        response.setHeader("Content-Disposition", "attachment")
Does this work properly in browsers without including the file name? What will be the suggested name of the file of the download like this?

2022-01-11 10:04 UTC, Rick-Ritense commented on zaak/src/main/kotlin/com/ritense/valtimo/portal/zaak/autoconfiguration/DocumentAutoConfiguration.kt
> +    fun documentResource(openZaakClient: OpenZaakClient): DownloadResource {
Yes you are right. I renamed the file, forgot about this method afterwards :)

2022-01-11 10:04 UTC, ivo-ritense requested changes
In general it looks like the biggest issue is the lack of security as far as i can tell. We need to make sure that the document has a link to a zaak that the user is related to.

2022-01-11 10:20 UTC, Rick-Ritense commented on zaak/src/main/kotlin/com/ritense/valtimo/portal/zaak/security/config/DocumentResourceHttpSecurityConfigurer.kt
> +                .antMatchers(GET, "/api/document/{documentId}/content").permitAll()
I will change it

2022-01-11 10:20 UTC, Rick-Ritense commented on zaak/src/main/kotlin/com/ritense/valtimo/portal/zaak/client/OpenZaakClient.kt
> +    fun webClient(): WebClient {
Before the getDocumentContentStream() was in another file That extended this class.
I forgot to revert it back to private afterwards

2022-01-11 10:20 UTC, Rick-Ritense commented on zaak/src/main/kotlin/com/ritense/valtimo/portal/zaak/service/DownloadService.kt
> +interface DownloadService {
I checked and that is the same setup as in valtimo-backend-libraries indeed. I will change it

2022-01-11 10:20 UTC, Rick-Ritense commented on zaak/src/main/kotlin/com/ritense/valtimo/portal/zaak/web/rest/DownloadResource.kt
> +        response.setHeader("Content-Disposition", "attachment")
Yes this should work according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

When a file name is provided it is used for a "Save As" dialog. But I can't be sure what type is document is being downloaded. That is why I left the filename blank

2022-01-11 12:41 UTC, ivo-ritense commented
> In general it looks like the biggest issue is the lack of security as far as i can tell. We need to make sure that the document has a link to a zaak that the user is related to.

After talking about it we agreed that the underlying document API is reponsible according to the design. Only think that is needed here is to ensure the user is authenticated.

2022-01-12 08:44 UTC, ivo-ritense approved these changes

2022-01-12 16:21 UTC, ivo-ritense approved these changes

2022-01-12 16:38 UTC, merged