52017 - Change query to retrieve Taken with identificatie
valtimo-platform/valtimo-portal-engine pull request #174
Opened 2023-02-06 18:55 UTC by theo-ritense

2023-02-07 07:39 UTC, Klaas-Ritense commented on gzac/objects-api/src/test/kotlin/com/ritense/valtimo/portal/gzac/objectsapi/task/graphql/TaskMutationIT.kt
> +                        if (dataAttrs.containsAll(listOf("identificatie.type__exact__bsn", "identificatie.value__exact__569312863"))) {
According to the [API specs](https://objecten-zgw.test.denhaag.nl/api/v2/schema/#tag/objects/operation/object_list), a nested object can be queried like this:
`identificatie__type__exact__bsn`

2023-02-07 08:15 UTC, theo-ritense commented on gzac/objects-api/src/test/kotlin/com/ritense/valtimo/portal/gzac/objectsapi/task/graphql/TaskMutationIT.kt
> +                        if (dataAttrs.containsAll(listOf("identificatie.type__exact__bsn", "identificatie.value__exact__569312863"))) {
I missed that part. Fixed!

2023-02-07 08:21 UTC, Klaas-Ritense commented on gzac/objects-api/src/main/kotlin/com/ritense/valtimo/portal/gzac/objectsapi/task/service/TaskService.kt
> +            }
This is a massive breaking change. The existing TaakConnector, will stop working. And there are several projects that use the TaakConnector in production.
Have we considered what we want to do with this

2023-02-07 10:00 UTC, theo-ritense commented on gzac/objects-api/src/main/kotlin/com/ritense/valtimo/portal/gzac/objectsapi/task/service/TaskService.kt
> +            }
@Klaas-Ritense Checked with Thomas, and it seems there 'is just 1 user of which none in production'.

2023-02-07 13:00 UTC, Klaas-Ritense requested changes
The 'identificatie__type' is also inside an array. Not sure if that works

2023-02-09 08:53 UTC, theo-ritense commented
That's an issue. It not in the spec, so we should expect it not to work.
@ThomasRitense can we change the TaakObject.identification to an object instead of a list/array?

2023-02-09 09:03 UTC, ThomasRitense commented
@theo-ritense Yes, please change from array to object.

2023-02-10 13:40 UTC, Klaas-Ritense approved these changes

2023-02-10 13:52 UTC, merged