Added configuration to support keycloak
valtimo-platform/valtimo-portal-engine pull request #59
Opened 2021-06-25 07:35 UTC by ivo-ritense

By default this is now using the valtimo test keycloak. Maybe we should include a keycloak instance in the docker compose file?

2021-06-28 07:51 UTC, Tom-Ritense requested changes

2021-06-28 07:51 UTC, Tom-Ritense commented on app/src/main/resources/config/application.yml
> +                    issuer-uri: https://keycloak.test.valtimo.nl/auth/realms/valtimo
deze server idd niet meer hanteren. Maar de prod variant https://keycloak.valtimo.nl

2021-06-28 07:51 UTC, Tom-Ritense commented on app/src/main/resources/config/application.yml
> +                    issuer-uri: https://keycloak.test.valtimo.nl/auth/realms/valtimo
Oja de comment kan dan ook weg lijkt mij

2021-06-29 08:07 UTC, Julia-Ritense approved these changes

2021-06-30 07:58 UTC, Tom-Ritense approved these changes

2021-06-30 11:31 UTC, merged