WIP: Added authentication to GraphQL context that is then used to retrieve cases
valtimo-platform/valtimo-portal-engine pull request #62
Opened 2021-07-01 07:32 UTC by ivo-ritense

- Authentication object is available in GraphQL context that can be injected in queries and mutations
- Authentication is used to determine userId that case list is filtered by

2021-07-01 07:42 UTC, Tom-Ritense requested changes

2021-07-01 07:42 UTC, Tom-Ritense commented on graphql/src/main/kotlin/com/ritense/valtimo/portal/graphql/context/AuthenticationGraphQLContextFactory.kt
> +@ExperimentalCoroutinesApi
Let op, op dit moment is er een public endpoint die geen security moet hebben. Dat is de query publicTask oid kan je die open stellen?

2021-07-01 07:42 UTC, Tom-Ritense commented on case/src/main/kotlin/com/ritense/valtimo/portal/case/service/CaseService.kt
>      fun getCase(id: CaseId): Case? {
Moet deze call dan ook niet op user id matchen? ik snap dat de lijst dit al doet maar als je vervolgens het id weet van iemand kan je daar dan ook bij?

2021-07-01 07:42 UTC, Tom-Ritense commented on graphql/src/main/kotlin/com/ritense/valtimo/portal/graphql/case/CreateCaseMutation.kt
> +        context: AuthenticationGraphQLContext
wordt dit geinject?

2021-07-01 07:42 UTC, Tom-Ritense commented on graphql/src/main/kotlin/com/ritense/valtimo/portal/graphql/context/AuthenticationGraphQLContext.kt
> +class AuthenticationGraphQLContext (val authentication : Authentication?, request: ServerRequest) : SpringGraphQLContext(request)
even gradle checks runnen om alle syntax dingen te fixen ik zie wat spaties teveel

2021-07-01 07:42 UTC, Tom-Ritense commented on graphql/src/main/kotlin/com/ritense/valtimo/portal/graphql/service/GraphqlService.kt
> +import java.util.*
* import doen we niet zie checks report of even je intelliJ config aanpassen.

2021-07-01 09:11 UTC, ivo-ritense commented on graphql/src/main/kotlin/com/ritense/valtimo/portal/graphql/case/CreateCaseMutation.kt
> +        context: AuthenticationGraphQLContext
Ja, GraphQLContext wordt automatisch geinject door de data fetcher zonder dat dit verschijnt als argument in the graphQL schema

2021-07-01 09:13 UTC, ivo-ritense commented on graphql/src/main/kotlin/com/ritense/valtimo/portal/graphql/context/AuthenticationGraphQLContext.kt
> +class AuthenticationGraphQLContext (val authentication : Authentication?, request: ServerRequest) : SpringGraphQLContext(request)
Die vind hem prima

2021-07-01 09:13 UTC, ivo-ritense commented on case/src/main/kotlin/com/ritense/valtimo/portal/case/service/CaseService.kt
>      fun getCase(id: CaseId): Case? {
Ja, daar was ik nog mee bezig

2021-07-06 07:34 UTC, ivo-ritense commented on graphql/src/main/kotlin/com/ritense/valtimo/portal/graphql/context/AuthenticationGraphQLContextFactory.kt
> +@ExperimentalCoroutinesApi
Ik heb nu de endpoint open gezet, en gebruik default een data fetcher die de spring authentication checkt. Je kan @IsUnauthenticated gebruiken om te zorgen dat het open staat

2021-07-08 11:17 UTC, Tom-Ritense approved these changes

2021-07-08 11:17 UTC, Tom-Ritense commented on graphql/src/main/kotlin/com/ritense/valtimo/portal/graphql/security/context/AuthenticationGraphQLContextFactory.kt
> +        val reactorContext = coroutineContext[ReactorContext]?.context ?:
liever 1line imo

2021-07-08 11:17 UTC, Tom-Ritense commented on graphql/src/main/kotlin/com/ritense/valtimo/portal/graphql/security/directive/ReactiveDataFactoryProvider.kt
> +            objectMapper = objectMapper)
) on next line

2021-07-08 11:17 UTC, ivo-ritense commented on graphql/src/main/kotlin/com/ritense/valtimo/portal/graphql/service/GraphqlService.kt
> +import java.util.*
Fixed

2021-07-08 14:18 UTC, merged